{% set name = "elasticsearch-dbapi" %}
{% set version = "0.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/elasticsearch-dbapi-{{ version }}.tar.gz
  sha256: 55175ed2869131eec8a6e890648395f22a6eabdfc1f42b7a632237135423f309

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - elasticsearch >7,<7.14
    - packaging >=21.0
    - sqlalchemy

test:
  imports:
    - es
    - es.elastic
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/preset-io/elasticsearch-dbapi
  summary: A DBAPI and SQLAlchemy dialect for Elasticsearch
  license: Apache-2.0
  license_file: LICENSE.txt
  dev_url: https://github.com/preset-io/elasticsearch-dbapi
  doc_url: https://github.com/preset-io/elasticsearch-dbapi

extra:
  recipe-maintainers:
    - xylar
